plugins {
    id "net.fabricmc.fabric-loom" version "1.17.20"
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation fileTree("libs/fabric-api") {
        include("*.jar")
    }
    implementation files(
        "libs/voicechat-fabric-2.6.22+26.2.jar",
        "libs/modmenu-20.0.1.jar",
        "libs/piper-jni-1.4.2.jar",
        "libs/jlayer-1.0.1.4.jar"
    )
    implementation("net.java.dev.jna:jna-platform:5.18.1")
    implementation("com.github.k2-fsa.sherpa-onnx:sherpa-onnx-jvm:v1.13.5")
    implementation("com.github.k2-fsa.sherpa-onnx:sherpa-onnx-native-lib-win-x64:v1.13.5")
    implementation("org.apache.commons:commons-compress:1.27.1")
    implementation("org.tukaani:xz:1.10")
    include("net.java.dev.jna:jna-platform:5.18.1")
    include("net.java.dev.jna:jna:5.18.1")
    include("com.github.k2-fsa.sherpa-onnx:sherpa-onnx-jvm:v1.13.5")
    include("com.github.k2-fsa.sherpa-onnx:sherpa-onnx-native-lib-win-x64:v1.13.5")
    include("org.apache.commons:commons-compress:1.27.1")
    include("org.tukaani:xz:1.10")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

processResources {
    filteringCharset = "UTF-8"
    inputs.property("version", project.version)
    filesMatching("fabric.mod.json") {
        expand("version": project.version)
    }
}

tasks.named("jar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(zipTree("libs/piper-jni-1.4.2.jar")) {
        exclude("META-INF/MANIFEST.MF")
        exclude("META-INF/*.SF")
        exclude("META-INF/*.RSA")
        exclude("META-INF/*.DSA")
    }
    from(zipTree("libs/jlayer-1.0.1.4.jar")) {
        exclude("META-INF/MANIFEST.MF")
        exclude("META-INF/maven/**")
    }
}
